### ISSUE TITLE
Code breaks for ints larger than 16-bits

### ISSUE THREAD

**Issue by zury-cutler** [shmulvad/fast-tsp#5]
I am attempting to use this module to find a tsp traverse for a set of float data. Since the module only accepts lists of lists of ints, I converted my data to this form and multiplied all my data by a larger scalar to help preserve some of the precision before casting to an int. I was getting crashes any time I multiplied by too large a number, but smaller scalars worked fine. 

So I manually narrowed down the number which caused a crash and found it to be anything >= 65536. This is the smallest unsigned int number that cannot be represented by 16-bits. It also appears to crash on any negative number. Leading me to the conclusion that this module does not work for signed ints or int values larger than 16 bits, which is a very annoying restriction considering it also must use ints and cannot read numpy arrays.

**Comment by shmulvad** [comment]
Hi @zury-cutler,

I am not interested in making it work for floating point numbers (it would make it slower, defeating its main selling point) and I would not support negative distances (that would violate the triangle inequality, which makes the problem very different and would require a complete rewrite).

I can understand why not supporting distances higher than 65,536 is annoying and might not allow for the precision needed to solve your problem.

This could either be solved by switching all necessary code in [`/src/tsp.h`](../blob/main/src/tsp.h) to use unsigned 32-bit ints (distances up to 2^32 = 4,294,967,296 should be enough for most purposes) or "solved" by simply checking what the min and max is in the distance matrix before doing any pure TSP-computation, and an exception with a clear error message is raised if any distance `d > UINT16_MAX` or `d < 0` is present.

I don't have the ressources to work on this currently, but if you want to make a PR for it, I would be happy to accept it.

**Comment by shmulvad** [comment]
I added some details to the documentation and a utility function for checking whether the distance matrix supplied is valid according to the requirements for the library. Will consider this closed.
